vich_uploader:
    db_driver: orm

    mappings:
       profilPicture:
           uri_prefix: /images/media
           upload_destination: '%kernel.project_dir%/public/images/media'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
