vich_uploader:
    db_driver: orm

    mappings:
       picture:
           uri_prefix: '%picture%'
           upload_destination: '%kernel.project_dir%/public%picture%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
